services:
  - type: web
    name: crypto-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app

  - type: worker
    name: crypto-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
